/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface Account {
  accessToken: string | null
  accessTokenExpiresAt: string | null
  accountId: string
  createdAt: Generated<string>
  id: string
  idToken: string | null
  password: string | null
  providerId: string
  refreshToken: string | null
  refreshTokenExpiresAt: string | null
  scope: string | null
  updatedAt: string
  userId: string
}

export interface ApiUsageLog {
  costJpy: number
  costUsd: number
  createdAt: Generated<string>
  exchangeRate: number
  id: string
  inputTokens: number
  metadata: string | null
  model: string
  operation: string
  outputTokens: number
  userId: string | null
}

export interface Session {
  createdAt: Generated<string>
  expiresAt: string
  id: string
  ipAddress: string | null
  token: string
  updatedAt: string
  userAgent: string | null
  userId: string
}

export interface User {
  createdAt: Generated<string>
  email: string
  emailVerified: Generated<number>
  id: string
  image: string | null
  isAnonymous: Generated<number>
  name: string
  updatedAt: string
}

export interface Verification {
  createdAt: Generated<string>
  expiresAt: string
  id: string
  identifier: string
  updatedAt: string
  value: string
}

export interface DB {
  account: Account
  apiUsageLog: ApiUsageLog
  session: Session
  user: User
  verification: Verification
}
